name: streams_channel3
description: StreamsChannel is inspired from EventChannel. It allows to create streams of events between Flutter and platform side.
version: 1.0.1
homepage: https://github.com/loup-v/streams_channel

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.loup.streams_channel
        pluginClass: StreamsChannelPlugin
      ios:
        pluginClass: StreamsChannelPlugin
